source "https://rubygems.org"

gem "rails", ">= 7.0", "< 9.0"
gem "rails_vue_vite", path: "../.."
gem "puma", ">= 5.0"
gem "simplecov", "~> 0.22", require: false
gem "simplecov-lcov", "~> 0.9", require: false
